### ISSUE TITLE
Does not work with react-storybook-addon-info

### ISSUE THREAD

**Issue by MrOrz** [storybooks/storyshots#17]
If a story is added with `addWithInfo`, the test will fail with the following error:

```
$ npm run test-storybook

> @kadira/react-button@1.0.2 test-storybook /Users/johsonliang/workspace/react-button
> storyshots

=> Loading custom .babelrc

Button

✗ default view: ERROR
  Invariant Violation: Objects are not valid as a React child (found: object with keys {name, render}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `Story`.
      at invariant (/Users/johsonliang/workspace/react-button/node_modules/fbjs/lib/invariant.js:38:15)
      at traverseAllChildrenImpl (/Users/johsonliang/workspace/react-button/node_modules/react/lib/traverseAllChildren.js:136:56)
      at traverseAllChildren (/Users/johsonliang/workspace/react-button/node_modules/react/lib/traverseAllChildren.js:164:10)
      at Object.ReactChildReconciler.instantiateChildren (/Users/johsonliang/workspace/react-button/node_modules/react/lib/ReactChildReconciler.js:71:7)
      at ReactMultiChild.Mixin._reconcilerInstantiateChildren (/Users/johsonliang/workspace/react-button/node_modules/react/lib/ReactMultiChild.js:189:41)
      at ReactMultiChild.Mixin.mountChildren (/Users/johsonliang/workspace/react-button/node_modules/react/lib/ReactMultiChild.js:228:27)
      at ReactTestComponent.mountComponent (/Users/johsonliang/workspace/react-button/node_modules/react/lib/ReactTestRenderer.js:53:8)
      at Object.ReactReconciler.mountComponent (/Users/johsonliang/workspace/react-button/node_modules/react/lib/ReactReconciler.js:47:35)
      at ReactMultiChild.Mixin.mountChildren (/Users/johsonliang/workspace/react-button/node_modules/react/lib/ReactMultiChild.js:240:44)
      at ReactTestComponent.mountComponent (/Users/johsonliang/workspace/react-button/node_modules/react/lib/ReactTestRenderer.js:53:8)
```

Steps to reproduce: 

```
$ git clone -b add-with-info https://github.com/MrOrz/react-button.git # See the diff with original react-button here: https://github.com/kadira-samples/react-button/compare/master...MrOrz:add-with-info
$ npm i
$ npm run test-storybook
```

**Comment by arunoda** [comment]
Seems like a React related issue. We will have a look at this.

**Comment by roonyh** [comment]
@arunoda it was a bug in our code :( Submitted the fix at #20

**Comment by MrOrz** [comment]
I updated storyshots to the latest version and now it is working :)
Thank you so much for the fix and your rapid response!

**Comment by tleunen** [comment]
hey @roonyh, I'm still having an issue with the latest version.

```
TypeError: (0 , _storybook.storiesOf)(...).addWithInfo is not a function
```

**Comment by tleunen** [comment]
Ok it seems that for storyshots, the order is important in the config file, so loading the addon first is very important :)
