### ISSUE TITLE
Storyshots crashes when it finds differences

### ISSUE THREAD

**Issue by chrish-21** [storybooks/storyshots#63]
Hi, Storyshots keeps crashing for me after testing when it found differences in the snapshots.

This is what happens when I run "npm run test-storybook"
- The first time the snapshots are created
- I run it again without changes and it works and tells me that the stories matched the snapshots
- I make a change and run it, and it gives me the test results but then it crashes. The output is the following:
```
> storyshot_test@0.1.0 test-storybook F:\Programming_Learning\storyshot_test
> storyshots


Welcome
✓ to Storybook

Button

✗ with text
  - Snapshot
  + Current story

    <button
      onClick={[Function]}
      style={
        Object {
          "backgroundColor": "#FFFFFF",
          "border": "1px solid #eee",
          "borderRadius": 3,
          "cursor": "pointer",
          "fontSize": 15,
          "margin": 10,
          "padding": "3px 10px",
        }
      }>
  -   Hello Button
  +   Hello
    </button>

✓ with some emoji

Test Summary
> 3 stories tested.
> 2/3 stories matched with snapshots.
> 1/3 differed from snapshots.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run
" "test-storybook"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! storyshot_test@0.1.0 test-storybook: `storyshots`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the storyshot_test@0.1.0 test-storybook script 'storyshots'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the storyshot_test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     storyshots
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs storyshot_test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls storyshot_test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Programming_Learning\storyshot_test\npm-debug.log
```
And here is the text from the npm-degug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test-storybook' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose run-script [ 'pretest-storybook', 'test-storybook', 'posttest-storybook' ]
5 info lifecycle storyshot_test@0.1.0~pretest-storybook: storyshot_test@0.1.0
6 silly lifecycle storyshot_test@0.1.0~pretest-storybook: no script for pretest-storybook, continuing
7 info lifecycle storyshot_test@0.1.0~test-storybook: storyshot_test@0.1.0
8 verbose lifecycle storyshot_test@0.1.0~test-storybook: unsafe-perm in lifecycle true
9 verbose lifecycle storyshot_test@0.1.0~test-storybook: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;F:\Programming_Learning\storyshot_test\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\libnvvp;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\PDFtk Server\bin\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\HashiCorp\Vagrant\bin;C:\Program Files\MongoDB\Server\3.2\bin;C:\Program Files (x86)\Brackets\command;C:\Program Files\nodejs\;C:\Users\Christian\AppData\Local\atom\bin;C:\Users\Christian\AppData\Local\Android\sdk\tools;C:\Users\Christian\AppData\Local\Android\sdk\platform-tools;C:\Users\Christian\AppData\Local\.meteor\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Christian\AppData\Roaming\npm
10 verbose lifecycle storyshot_test@0.1.0~test-storybook: CWD: F:\Programming_Learning\storyshot_test
11 silly lifecycle storyshot_test@0.1.0~test-storybook: Args: [ '/d /s /c', 'storyshots' ]
12 silly lifecycle storyshot_test@0.1.0~test-storybook: Returned: code: 1  signal: null
13 info lifecycle storyshot_test@0.1.0~test-storybook: Failed to exec test-storybook script
14 verbose stack Error: storyshot_test@0.1.0 test-storybook: `storyshots`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid storyshot_test@0.1.0
16 verbose cwd F:\Programming_Learning\storyshot_test
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test-storybook"
19 error node v6.9.2
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error storyshot_test@0.1.0 test-storybook: `storyshots`
22 error Exit status 1
23 error Failed at the storyshot_test@0.1.0 test-storybook script 'storyshots'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the storyshot_test package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     storyshots
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs storyshot_test
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls storyshot_test
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

To test this:
- I created a new app using create-react-app
- installed Storybook (I tried it twice once in the 'Quick Start Guide' and once in the 'Slow Start Guide' way)
- installed Storyshots following https://getstorybook.io/docs/react-storybook/testing/structural-testing
- then i run the snapshots as desribed above with the only changes being to the Text of the button that is provided by the example

What might also be important:
When I install storybook I always get an error the first time installing it, both in the 'Slow' and the 'Quick' Way.

- For the 'Fast' Way:
I run "getstorybook" and it gives me the following error:
```
• Installing dependencies. ✖

    An error occurred while installing dependencies.
```
Then I run "npm i" manually and everything installs properly

- For the 'Slow' way:
The first time I run "npm i --save-dev @kadira/storybook" I get the following output:
```
story-test@0.1.0 F:\Programming_Learning\story-test
+-- @kadira/storybook-addon-actions@1.1.1  extraneous
+-- @kadira/storybook-addon-links@1.0.1  extraneous
+-- @kadira/storybook-addons@1.6.1  extraneous
+-- @kadira/storybook-channel-postmsg@2.0.1  extraneous
+-- airbnb-js-shims@1.0.1  extraneous
+-- babel-plugin-react-docgen@1.4.1  extraneous
+-- common-tags@1.4.0  extraneous
+-- configstore@2.1.0  extraneous
+-- lodash._createcompounder@3.0.0  extraneous
+-- lodash.pick@4.4.0  extraneous
+-- react-modal@1.6.3  extraneous
+-- rechoir@0.6.2  extraneous
+-- redux@3.6.0  extraneous
+-- serve-favicon@2.3.2  extraneous
`-- webpack-hot-middleware@2.13.2  extraneous

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"an
y"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.14 (node_modules\react-scripts\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"an
y"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
"--save-dev" "@kadira/storybook"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! path F:\Programming_Learning\story-test\node_modules\.staging\@kadira\react-split-pane-beabcc68
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'F:\Programming_Learning\story-test\node_modules\.staging\@kadira
\react-split-pane-beabcc68' -> 'F:\Programming_Learning\story-test\node_modules\@kadira\react-split-pane'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'F:\Programming_Learning\story-test\node_modules\.staging\@kadira
\react-split-pane-beabcc68' -> 'F:\Programming_Learning\story-test\node_modules\@kadira\react-split-pane'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'F:\Programming_Learning\story-test\node_modules\.staging\@kad
ira\react-split-pane-beabcc68' -> 'F:\Programming_Learning\story-test\node_modules\@kadira\react-split-pane'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'F:\Programming_Learning\story-test\node_modules\.staging\@kadira
\react-split-pane-beabcc68' -> 'F:\Programming_Learning\story-test\node_modules\@kadira\react-split-pane'
npm ERR!     at Error (native) parent: 'story-test' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Programming_Learning\story-test\npm-debug.log
```
Then I run the exactly the same command again and it installs properly.

I have also tried to reinstall node and npm as well as running "npm cache clean" but so far I couldn't fix the problem.

**Comment by danieltott** [comment]
I have this same problem (minus the install problems). Using create-react-app, all my dependencies are up to date. Running on Sierra, with node v6.9.1

**Comment by chrish-21** [comment]
I'm pretty sure now that my install problems are an unrelated problem. This happened now on a few different projects with different packages and I often have to run the install command twice.

So the second part of my initial post is irrelevant, however the original problem still exists for me.

**Comment by roonyh** [comment]
@chrish-21 Storyshots works like any other test tool. If the snapshots does not match that is a test fail. So it reports it by returning a non zero exit code. This helps for example ci services to report back to you a test failure. This is not storyshots crashing. Its the expected behaviour.

**Comment by chrish-21** [comment]
Oh, okay didn't know that, thank you! Always something new to learn ;)

**Comment by bitflorist** [comment]
sorry, to reopen this, but on jest / snapshot, the behavior is normally asking to update the snapshot.
How would you update the snapshot?

Shouldn't it fail more gracefullyt then?

```
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test-storybook"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ test-storybook: `storyshots`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ test-storybook script 'storyshots'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     storyshots
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/myproject/assets/npm-debug.log
```

**Comment by bitflorist** [comment]
UPDATE: solved, I refer to this great articel which describes all the options, which I successfully run now.
https://voice.kadira.io/snapshot-testing-in-react-storybook-43b3b71cec4f#.jc66i94bw

watch and interactive mode: yeah!
```
 npm run test-storybook -- -w -i
```
