### ISSUE TITLE
How to use with storybook-addon-knobs decorator?

### ISSUE THREAD

**Issue by kenta88** [storybooks/storyshots#74]
Hi everyone,

I started to use storyshots for Structural Testing inside a react storybook project. 

Unfortunately I discovered that the new version of storyshots (3.2.0) doesn't work with decorator. 
Here following an example of issue:

` ● Storyshots › Elements › Button

    TypeError: Cannot read property 'on' of null
      
      at WrapStory.componentDidMount (node_modules/@kadira/storybook-addon-knobs/dist/components/WrapStory.js:53:25)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:265:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:206:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:153:16)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:140:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:97:27)
      at Object.render [as create] (node_modules/react-test-renderer/lib/ReactTestMount.js:125:18)
      at Object.<anonymous> (node_modules/storyshots/dist/index.js:103:56)
      at process._tickCallback (internal/process/next_tick.js:103:7)
`

Without the decorator it works in the proper way.

I tried to use the previus version of storyshots and it seems works properly:

`Test Summary
> 28 stories tested.
> 28/28 stories matched with snapshots.
`

Just now I'm going to use the older version. If anyone have some suggestion how to work around this issue with the new version let me know.

Thanks

**Comment by arunoda** [comment]
@roonyh could you have a look at this?

**Comment by lewisf** [comment]
this looks like its affecting other addons as well. any idea when this will get released?

(talking about the merged linked ticket)

**Comment by roonyh** [comment]
v3.2.1 carries a fix for this. Sorry about taking so long to release.
