### ISSUE TITLE
Cannot read property 'decelerationRate' of undefined

### ISSUE THREAD

**Issue by xareelee** [storybooks/storyshots#86]
When I use jest/storyshots to run the snapshot tests. It shows an abnormal error (`TypeError: Cannot read property 'decelerationRate' of undefined `):

```
 FAIL  storybook/Storyshots.test.js
  ● Storyshots › [Page] CountryPolicy › entry

    TypeError: Cannot read property 'decelerationRate' of undefined
      
      at Object.<anonymous> (node_modules/react-native/Libraries/Components/WebView/WebView.ios.js:555:3254)
      at Object.get WebView [as WebView] (node_modules/react-native/Libraries/react-native/react-native.js:68:22)
      at CountryPolicy (src/ui/CountryPolicy/CountryPolicy.js:11:43)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:306:16
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at ReactCompositeComponentWrapper._constructComponentWithoutOwner (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:305:14)
      at ReactCompositeComponentWrapper._constructComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:280:21)
```

Source code:

```js
// CountryPolicy.jsx
const CountryPolicy = () => (
  <WebView
    style={styles.wrapper}
    source={{ uri: policyUrl }}
  />
) 
```

Story:

```jsx
// CountryPolicy.stories.js
storiesOf('[Page] CountryPolicy', module)
  .add('entry', () => (
    <CountryPolicy />
  ));
```

The app displays normally. It seems something wrong when testing a DOM containing a `WebView`.

**Comment by jrdrg** [comment]
Possibly the same issue referenced in https://github.com/storybooks/storyshots/pull/76?
